spring:
  application:
    name: shipping-tracking-app
  datasource:
    username: root
    password: Ralphses1234
    url: jdbc:mysql://localhost:3306/shipping_order_app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true